### ISSUE TITLE
Learn what tech recruiters want and how do they pay for referrals

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2252]
- [x] Connect with Alberto Cardinalli Jr. <cardinallijr@gmail.com> to learn how he makes money referring candidates to recruitment firms
  - [X] Sent email to schedule Skype
  - [x] Had Skype conversation
- [ ] Connect with Ana Lins <ana@vanhack.com>
  - [X] Sent email to schedule Skype
  - [ ] Had Skype conversation <- She replied saying not interested

Articles/Videos on How the recruitment industry works:
- https://www.news.com.au/finance/work/former-recruitment-agent-spills-details-on-what-really-goes-on-in-the-industry/news-story/b6efeb3aba8e8ae23c1f3bd3ead66bac
- https://www.linkedin.com/pulse/working-recruitment-good-bad-ugly-roberto-monfardini/
- https://triplebyte.com/candidate_faq
- https://triplebyte.com/blog/announcing-our-35-million-series-b (on the future of Triplebyte)

**Comment by grumo** [comment]
@shervine here are the notes from Alberto Cardinalli's Skype conversation:
(Alberto has been in tech recruitment for

Notes:
- Most companies don't like to work with recruiters
- Companies rather work with their own HR departments because they get better leads as they understand the company needs/culture better
- Recruiting is very job/company specific, this means companies expect candidates that have been filtered for a specific job and specific cultural fit
- Cultural fit is paramount and cannot be automated
- Great recruiters devote a lot of time to screen and filter candidates manually
- This means a high touch approach works best which makes it very hard to automate. ie: How do you automate assessing cultural fit or the signal obtained from a one-to-one face interaction?
- Most companies like to work with only 2 or 3 recruiters they really trust
- Building relationships with companies takes time because building trust takes time
- Recruiters spend months going to events/meetups to find and build relationships with HR managers and tech managers
- Recruiters in general have a bad rep for being too pushy and annoying
- Alberto says he gets calls from recruiters all the time to meet for coffee. They are very insistent even when Alberto tells them that they are not hiring anyone.
- Alberto says there will always be work for recruiters because they are necessary evil because currently there is no way to automate the hiring process. Specifically assessing cultural fit can only be done on one-on-one interactions
- Companies work with recruiters not because they want to but precisely because hiring is a very time consuming process. They simply don't have the bandwidth to go through all the filtering process.
- Neither companies or recruiters will pay for leads that have not been interviewed face to face. In other words, they won't pay for leads coming from an automated assessment tool like Mench
- Companies pay for work that doesn't scale (ie: face to face time). They don't need assessment tools since they can easily use existing ones or build their own.

** Conclusions
- Recruiters do the hard work companies can't or don't want to do (ie: filtering through thousands of resumes and spending time conducting face-face interactions)
- Companies won't pay money to Mench unless Mench does the non-scalable work required in recruitment
- Therefore, our current plan to make money referring our top talent won't work unless we individually interview each candidate (this is what Triplebyte does)

**Comment by shervine** [comment]
@grumo Great summary and updates. I was never under the impression that we would auto-refer top students to companies as I do agree that a manual screening process is necessary. Our technology will not replace manual recruitment work, but complement it instead.

I remember when I was talking to my friend Tinthi (Who was a recruiter) she was also mentioning the importance of culture fit. She was even saying that some companies are racist as they want a specific type of people to join their group. But whatever the "culture" criteria is, we can understand it better by building the right intent tree and then doing the manual interview on top of that to fine tune our approach.

So as a recruiter, I don't see us automating everything, but instead, we would use our education technology as a lead-generation engine that gives us unique leads that no other recruiter has (over time, as we grow our student base) and then use our technology to understand things about our leads that no other platform understands simply because of the nature of the intent tree and how specific we can get with the questions we ask.

Let me know if this makes sense to you and if you share this view.

**Comment by grumo** [comment]
Closing for now as not related to top priority of getting companies to use Mench as a candidate selection tool.
